---
# tasks file for vm-consul-config

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags: debug_info

- name: Add all host ips to the security group in AWS if necessary.
  run_once: true
  ansible.builtin.template: 
    src: 'add_all_consul_nodes_include_my_pubip_to_security_group_aws.py.j2'
    dest: 'output/add_all_consul_nodes_include_my_pubip_to_security_group_aws.py'