---
- name: Starting the installation
  hosts: localhost
  tasks:
  - name: Set default values for variables
    ansible.builtin.include_vars:
      dir: env-defaults/
      extensions:
        - 'yml'

  - name: Include all .yml files from env-selection/
    ansible.builtin.include_vars:
      dir: env-selection/
      extensions:
        - 'yml'

  - name: Provision nodes for Consul DC1
    include_role:
      name: 'roles/provision-nodes'
    when: CONSUL_VM_DC1_PROVISION | bool
    vars:
        DC_ROLE: "consul"
        DC: "DC1"

  - name: Provision nodes for Consul DC2 if required
    include_role:
      name: 'roles/provision-nodes'
    when: CONSUL_VM_DC2_PROVISION | bool
    vars:
        DC_ROLE: "consul"
        DC: "DC2" 

  - name: Provision nodes for Consul DC3 if required
    include_role:
      name: 'roles/provision-nodes'
    when: CONSUL_VM_DC3_PROVISION | bool
    vars:
       DC_ROLE: "consul"
       DC: "DC3" 

  - name: Wait for SSH to come up on the newly created EC2 nodes
    local_action: wait_for
                  host={{ hostvars[item]['ansible_host'] }}
                  port=22
                  state=started
    with_items: "{{ groups['consul_nodes'] }}"


- name: Install required packages
  hosts: all
  tasks:
  - name: Set default values for variables
    ansible.builtin.include_vars:
      dir: env-defaults/
      extensions:
        - 'yml'

  - name: Include all .yml files from /Users/vyanamandra/survival/ansible/venus/env-selection/
    ansible.builtin.include_vars:
      dir: env-selection/
      extensions:
        - 'yml'

  - name: Install Consul binary all provisioned nodes for Consul
    include_role:
      name: 'roles/install-consul'
    when: CONSUL_VM_DC1_ENABLED | bool

  - name: Install Envoy binary on all provisioned nodes, required only on agent nodes running sidecars
    include_role:
      name: 'roles/install-envoy'
    when: CONSUL_VM_DC1_ENABLED | bool

  - name: Install Python 3.x and virtualenv on all provisioned nodes, required only on nodes running custom python apps
    include_role:
      name: 'roles/install-python'
    when: CONSUL_VM_DC1_ENABLED | bool

  - name: Setup consul server agent configs in DC1, client agent configs and create required dirs
    include_role:
      name: 'roles/setup-consul-config'
    when: CONSUL_VM_DC1_ENABLED | bool
    vars:
        DC: "DC1"

  - name: Setup consul server agent configs in DC2, client agent configs and create required dirs
    include_role:
      name: 'roles/setup-consul-config'
    when: CONSUL_VM_DC2_ENABLED | bool
    vars:
        DC: "DC2"

  - name: Setup consul server agent configs in DC3, client agent configs and create required dirs
    include_role:
      name: 'roles/setup-consul-config'
    when: CONSUL_VM_DC3_ENABLED | bool
    vars:
        DC: "DC3"

  - name: Connect the DCs in a Traditional WAN Federation (Simple Mesh - consul join -wan)
    include_role:
      name: 'roles/consul-join-clusters-traditional'
    when: CONSUL_TRADITIONAL_MESH_ENABLED | bool
    
  - name: Connect the DCs using a Mesh Gateway (with mode local)
    include_role:
      name: 'roles/consul-join-clusters-gateway'
    when: CONSUL_MESH_GATEWAY_ENABLED | bool

##  - name: Install Venus Python Apps and register those with Consul.
##    include_role:
##      name: 'roles/venus-py'
##    when: CONSUL_VM_ENABLED | bool
#
##  - name: Start Venus Python Apps and their sidecars
##    include_role:
##      name: 'roles/venus-py-scs'
##   when: CONSUL_VM_ENABLED | bool
