---
# tasks file for vm-consul-config

- name: Display all variables/facts known for a host
  debug:
    var: hostvars[inventory_hostname]
  tags: debug_info

- name: get private ip of each of the hosts
  register: "private_ip"
  become: true
  when: "'venus_dc_vm_ec2_nodes' in group_names"
  ansible.builtin.shell:
    cmd: hostname -i

- template:
    src: consul-server.config
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: "u=rw,g=r,o=r"
  when: "'venus_dc_vm_ec2_servers' in group_names"
  become: true

- template:
    src: consul-client.config
    dest: /etc/consul.d/consul.hcl
    owner: consul
    group: consul
    mode: "u=rw,g=r,o=r"
  when: "'venus_dc_vm_ec2_clients' in group_names"
  become: true

- name: Replace single quotes with double quotes
  become: true
  when: "'venus_dc_vm_ec2_nodes' in group_names"
  ansible.builtin.shell:
    cmd: sed -i "s/'/\"/g" /etc/consul.d/consul.hcl

- name: restart Consul service
  become: true
  when: "'venus_dc_vm_ec2_nodes' in group_names"
  ansible.builtin.systemd_service:
    name: consul
    state: restarted

- name: Bootstrap consul
  become: true
  run_once: yes
  when: "'venus_dc_vm_ec2_mgmt' in group_names"
  register: "bootstrap_token"
  ansible.builtin.shell:
    cmd: consul acl bootstrap  | grep ^SecretID | tr -d ' ' | awk -F ':' '{print $2}'
  
- debug: var=bootstrap_token

- name: Query consul members
  when: "'venus_dc_vm_ec2_mgmt' in group_names"
  register: "consul_members"
  ansible.builtin.shell:
    cmd: CONSUL_HTTP_TOKEN={{ bootstrap_token.stdout }} consul members

- debug: var=consul_members
