# Task that will be used to Launch/Create an EC2 Instance

- name: Update apt cache
  become: true
  when: "'consul_nodes' in group_names"
  apt:
    update_cache: yes

- name: Install the latest python3 package
  become: true
  when: "'consul_nodes' in group_names"
  ansible.builtin.apt:
    name: python3
    state: present

- name: Install the latest python3-pip package
  become: true
  when: "'consul_nodes' in group_names"
  ansible.builtin.apt:
    name: python3-pip
    state: present

- name: Install python virtualenv package
  become: true
  when: "'consul_nodes' in group_names"
  ansible.builtin.shell:
    cmd: pip3 install virtualenv

- name: Create a virtualenv named venv so we can operate under it
  become: true
  when: "'consul_nodes' in group_names"
  ansible.builtin.shell:
    cmd: virtualenv ~/venv

- name: Now make sure this virtualenv is forked every time root user is logged in
  become: true
  ansible.builtin.shell:
    cmd: echo '. ~/venv/bin/activate' >> ~/.bashrc
  when: "'consul_nodes' in group_names"
