---
# tasks file for vm-ec2

- name: Create the output/utils/vm-ec2 directory
  ansible.builtin.file:
    path: 'output/utils/vm-ec2'
    state: directory

- name: Fill and place utils/vm-ec2/create_machines.tf in output/utils/vm-ec2
  ansible.builtin.template:
    src: 'create_machines.tf'
    dest: 'output/utils/vm-ec2'
    mode: '0644'
  when: CONSUL_VM_EC2_CREATE_NODES | bool

- terraform:
    project_path: 'output/utils/vm-ec2'
    force_init: true
    state: present

- name: Execute Python Script using the shell module
  ansible.builtin.shell:
    cmd: python utils/scripts/add_ec2_to_config.py -d {{ DC_NORMALIZED }} -i {{ playbook_dir }}/inventory/hosts -l output/utils/vm-ec2 -s 3 -c 1 -t vm_ec2 -k /Users/vyanamandra/.ssh/amy-test.pem
  when: CONSUL_VM_EC2_CREATE_NODES | bool

- meta: refresh_inventory

- name: Print list of hosts
  ansible.builtin.debug:
    var: "{{ item }}"
  with_items: "{{ groups['venus_dc_vm_ec2_nodes'] }}"
    
#                host={{ item }}
- name: Wait for SSH to come up on the newly created EC2 nodes
  local_action: wait_for
                host="54.185.160.71"
                port=22
                state=started
  with_items: "{{ groups['venus_dc_vm_ec2_nodes'] }}"
  when: CONSUL_VM_EC2_CREATE_NODES | bool
