---
# tasks file for consul-join-clusters-gateway
- name: Set the fact that CONSUL_VM_MESH_FEDERATED is true
  set_fact:
    CONSUL_VM_MESH_FEDERATED: True

- name: Set the fact that CONSUL_VM_FEDERATED is true
  set_fact:
    CONSUL_VM_FEDERATED: True

- name: Stop consul service on all Consul Nodes
  become: true
  when: ("consul_nodes" in group_names)
  ansible.builtin.systemd_service:
    name: consul
    state: stopped

- name: Get the CA.pem from DC1
  become: true
  ansible.builtin.shell: 
    cmd: cat /opt/consul/tls/consul-agent-ca.pem
  register: mgmt_tls_ca_pem_dc1
  when: CONSUL_VM_TLS_ENABLED|bool and PRIMARY_DC_MGMT in group_names
  
- name: Get the CA.pem from DC2
  become: true
  ansible.builtin.shell: 
    cmd: cat /opt/consul/tls/consul-agent-ca.pem
  register: mgmt_tls_ca_pem_dc2
  when: CONSUL_VM_TLS_ENABLED|bool and inventory_hostname in (groups[SECONDARY_DC2_MGMT] if CONSUL_VM_DC2_ENABLED |bool else [])

- name: Get the CA.pem from DC3
  become: true
  ansible.builtin.shell: 
    cmd: cat /opt/consul/tls/consul-agent-ca.pem
  register: mgmt_tls_ca_pem_dc3
  when: CONSUL_VM_TLS_ENABLED|bool and inventory_hostname in (groups[SECONDARY_DC3_MGMT] if CONSUL_VM_DC3_ENABLED |bool else [])
  
  #inventory_hostname in ((groups[PRIMARY_DC_MGMT] + groups[SECONDARY_DC2_MGMT] if CONSUL_VM_DC2_ENABLED |bool else None + groups[SECONDARY_DC3_MGMT] if CONSUL_VM_DC3_ENABLED|bool else None ) | unique)

- name: Append DC1 CA.pem contents to DC2 and DC3 CA.PEM files
  become: true
  ansible.builtin.shell:
   cmd: echo "{{ groups[PRIMARY_DC_MGMT] | map('extract', hostvars, 'mgmt_tls_ca_pem_dc1') | map(attribute='stdout', default='') | list | select | join('') }}" >> /opt/consul/tls/consul-agent-ca.pem
  when: CONSUL_VM_TLS_ENABLED|bool and (inventory_hostname in (((groups[SECONDARY_DC2_NODES] if CONSUL_VM_DC2_ENABLED|bool else []) + (groups[SECONDARY_DC3_NODES] if CONSUL_VM_DC3_ENABLED|bool else []))|unique))

- name: Append DC2 CA.pem contents to DC3 and DC1 CA.PEM files
  become: true
  ansible.builtin.shell:
   cmd: echo "{{ groups[SECONDARY_DC2_MGMT] | map('extract', hostvars, 'mgmt_tls_ca_pem_dc2') | map(attribute='stdout', default='') | list | select | join('') }}" >> /opt/consul/tls/consul-agent-ca.pem
  when: CONSUL_VM_TLS_ENABLED|bool and (inventory_hostname in (((groups[SECONDARY_DC3_NODES] if CONSUL_VM_DC3_ENABLED|bool else []) + groups[PRIMARY_DC_NODES])|unique))

- name: Append DC3 CA.pem contents to DC1 and DC2 CA.PEM files
  become: true
  ansible.builtin.shell:
   cmd: echo "{{ groups[SECONDARY_DC3_MGMT] | map('extract', hostvars, 'mgmt_tls_ca_pem_dc3') | map(attribute='stdout', default='') | list | select | join('') }}" >> /opt/consul/tls/consul-agent-ca.pem
  when: CONSUL_VM_TLS_ENABLED|bool and CONSUL_VM_DC3_ENABLED|bool and (inventory_hostname in (((groups[SECONDARY_DC2_NODES] if CONSUL_VM_DC2_ENABLED|bool else []) + groups[PRIMARY_DC_NODES])|unique))

- name: Add a new line to ca.pem
  become: true 
  ansible.builtin.shell:
    cmd: echo "" >> /opt/consul/tls/consul-agent-ca.pem
  when: CONSUL_VM_TLS_ENABLED|bool and ("consul_nodes" in group_names)

- name: Get the DC name from each of the nodes.
  become: true
  when: ("consul_nodes" in group_names)
  ansible.builtin.shell:
    cmd: grep -h '^datacenter' /etc/consul.d/consul-common.hcl | cut -f 2 -d '"'
  register: this_dc_name

- name: Register the acl replication token
  become: true
  when: PRIMARY_DC_MGMT in group_names and CONSUL_VM_ACL_ENABLED|bool
  ansible.builtin.shell:
    cmd: cat /root/acl-replication-token.txt | grep '^SecretID' | tr -d ' ' | awk -F ':' '{print $2}'
  register: acl_replication_token

- name: Register the mesh gateway token
  become: true
  when: PRIMARY_DC_MGMT in group_names and CONSUL_VM_ACL_ENABLED|bool 
  ansible.builtin.shell:
    cmd: cat /root/mesh-gateway-token.txt | grep '^SecretID' | tr -d ' ' | awk -F ':' '{print $2}'
  register: mesh_gateway_token

- name: Templated copy of ACL that now has enable_token_replication = true
  become: true
  template: 
    src: "{{ playbook_dir }}/roles/consul-common-templates/templates/consul-acl.hcl.j2"
    dest: "/etc/consul.d/consul-acl.hcl"
  when: (CONSUL_VM_FEDERATED|bool) and ("consul_nodes" in group_names)

- name: Templated copy of consul-federation.hcl.j2 for primary_datacenter & without the key retry_join_wan set.
  become: true
  template: 
    src: "{{ playbook_dir }}/roles/consul-common-templates/templates/consul-federation.hcl.j2"
    dest: "/etc/consul.d/consul-federation.hcl"
  when: inventory_hostname in ((groups[PRIMARY_DC_SERVERS] + (groups[SECONDARY_DC2_SERVERS] if (CONSUL_VM_DC2_ENABLED|bool) else []) + (groups[SECONDARY_DC3_SERVERS] if (CONSUL_VM_DC3_ENABLED|bool) else [])) | unique)

- name: Templated copy of consul-connect.hcl.j2 to set primary_gateway
  become: true
  template: 
    src: "{{ playbook_dir }}/roles/consul-common-templates/templates/consul-connect.hcl.j2"
    dest: "/etc/consul.d/consul-connect.hcl"
  when: inventory_hostname in (((groups[SECONDARY_DC2_SERVERS] if (CONSUL_VM_DC2_ENABLED|bool) else []) + (groups[SECONDARY_DC3_SERVERS] if (CONSUL_VM_DC3_ENABLED|bool) else [])) | unique)

- name: Templated copy of mesh-gateway.env to /opt/consul/systemctl-service-configs/
  become: true
  template: 
    src: "{{ playbook_dir }}/roles/consul-common-templates/templates/mesh-services/mesh-gateway.env.j2"
    dest: "/opt/consul/systemctl-service-configs/mesh-gateway.env"
  when: inventory_hostname in ((groups[PRIMARY_DC_MGW] + (groups[SECONDARY_DC2_MGW] if (CONSUL_VM_DC2_ENABLED|bool) else []) + (groups[SECONDARY_DC3_MGW] if (CONSUL_VM_DC3_ENABLED|bool) else [])) | unique)

- name: Templated copy of mesh-gateway.service
  become: true
  template: 
    src: "{{ playbook_dir }}/roles/consul-common-templates/templates/mesh-services/mesh-gateway.service.j2"
    dest: "/lib/systemd/system/mesh-gateway.service"
  when: inventory_hostname in ((groups[PRIMARY_DC_MGW] + (groups[SECONDARY_DC2_MGW] if (CONSUL_VM_DC2_ENABLED|bool) else []) + (groups[SECONDARY_DC3_MGW] if (CONSUL_VM_DC3_ENABLED|bool) else [])) | unique)

- name: Get the Gossip encryption key from the Primary DC Mgmt server
  become: true
  ansible.builtin.shell:
    cmd: grep '^encrypt' /etc/consul.d/gossip-encryption.hcl | cut -f 2 -d '"'
  when: CONSUL_VM_GOSSIP_ENABLED|bool and PRIMARY_DC_MGMT in group_names
  register: "primary_gossip_encryption_token"

- name: Set primary_encrypt_key
  set_fact: 
    primary_encrypt_key: "{{ primary_gossip_encryption_token['stdout'] }}"
  when: CONSUL_VM_GOSSIP_ENABLED|bool and PRIMARY_DC_MGMT in group_names

- name: Set encrypt token ("encrypt = \"{{ groups[PRIMARY_DC_MGMT] | map('extract', hostvars, 'primary_encrypt_key') | list | join('') }}\"") the same on all DCs.
  become: true
  ansible.builtin.replace:
    path: /etc/consul.d/gossip-encryption.hcl
    regexp: '^encrypt.*'
    replace: "encrypt = \"{{ groups[PRIMARY_DC_MGMT] | map('extract', hostvars, 'primary_encrypt_key') | list | join('') }}\""
  when: CONSUL_VM_GOSSIP_ENABLED|bool and ("consul_nodes" in group_names)

- name: Remove serf/remote.keyring files from all DCs.
  become: true
  ansible.builtin.file:
    path: /opt/consul/data-dir/serf/remote.keyring
    state: absent 
  when: CONSUL_VM_GOSSIP_ENABLED|bool and "consul_nodes" in group_names

- name: Remove serf/local.keyring files from all DCs.
  become: true
  ansible.builtin.file:
    path: /opt/consul/data-dir/serf/local.keyring
    state: absent 
  when: CONSUL_VM_GOSSIP_ENABLED|bool and "consul_nodes" in group_names

- name: Replace single quotes with double quotes
  become: true
  when: ("consul_nodes" in group_names)
  ansible.builtin.shell:
    cmd: for f in $(ls /etc/consul.d/*.hcl); do sed -i "s/'/\"/g" "${f}"; done

- name: Set group and owner to Consul over /etc/consul.d 
  become: true
  file: dest=/etc/consul.d owner=consul group=consul recurse=yes

- name: Set group and owner to Consul over /opt/consul
  become: true
  file: dest=/opt/consul owner=consul group=consul recurse=yes

- name: Start consul service on all Consul Nodes
  become: true
  when: ("consul_nodes" in group_names)
  ansible.builtin.systemd_service:
    name: consul
    state: started

- name: Get the Bootstrap token from the primary DC 
  become: true
  when: PRIMARY_DC_MGMT in group_names and CONSUL_VM_ACL_ENABLED|bool
  ansible.builtin.shell:
    cmd: . ~/.bashrc 2>/dev/null && echo $CONSUL_HTTP_TOKEN
  register: primary_bootstrap_token

- name: Set primary_bootstrap_token_fact
  set_fact: 
    primary_bootstrap_token_fact: '{{ groups[PRIMARY_DC_MGMT] | map("extract", hostvars, "primary_bootstrap_token") | map(attribute="stdout", default="") | list | select | join("") }}'
  when: CONSUL_VM_ACL_ENABLED|bool

- name: Just force systemd to reread configs on the Primary DC's mesh gateway first (2.4 and above)
  become: true
  ansible.builtin.shell:
    cmd: systemctl daemon-reload
  when: PRIMARY_DC_MGW in group_names

- name: Start the mesh gateway service on the primary first.
  become: true
  when: PRIMARY_DC_MGW in group_names
  ansible.builtin.systemd_service:
    name: mesh-gateway
    state: started

- name: Templated copy of mesh-gateway.service
  become: true
  template: 
    src: "{{ playbook_dir }}/roles/consul-common-templates/templates/mesh-services/mesh-proxy-defaults.hcl.j2"
    dest: "/root/mesh-proxy-defaults.hcl"
  when: PRIMARY_DC_MGMT in group_names

- name: Config write /root/mesh-proxy-defaults.hcl to ensure the mesh gateway proxy mode is taken care of. 
  become: true
  ansible.builtin.shell:
    cmd: . ~/.bashrc 2>/dev/null && consul config write /root/mesh-proxy-defaults.hcl
  when: PRIMARY_DC_MGMT in group_names

- name: Check if secondary dcs have started replicating tokens.
  become: true
  when: CONSUL_VM_ACL_ENABLED|bool and inventory_hostname in (((groups[SECONDARY_DC2_MGW] if (CONSUL_VM_DC2_ENABLED|bool) else []) + (groups[SECONDARY_DC3_MGW] if (CONSUL_VM_DC3_ENABLED|bool) else [])) | unique)
  ansible.builtin.shell:
    cmd: for x in $(seq 1 30); do if [[ $(curl -sk -H "{{ 'X-Consul-Token:' + primary_bootstrap_token_fact}}" {{CONSUL_HTTP_ADDR_LOC}}/v1/acl/replication -o- | python -m json.tool | grep 'ReplicatedTokenIndex' | awk '{print $2}') -gt 3 ]]; then echo 'This consul cluster has replicated tokens from the primary dc.'; break; else echo 'The cluster has not yet spoken to the primary_dc or replicated tokens from there. Sleeping for 5 seconds before checking again'; sleep 5; fi; done

- name: Now start the mesh gateway service on the secondary dcs.
  become: true
  when: inventory_hostname in (((groups[SECONDARY_DC2_MGW] if (CONSUL_VM_DC2_ENABLED|bool) else []) + (groups[SECONDARY_DC3_MGW] if (CONSUL_VM_DC3_ENABLED|bool) else [])) | unique)
  ansible.builtin.systemd_service:
    name: mesh-gateway
    state: started

- name: Set the bootstrap token within .bashrc of all Consul Nodes
  become: true
  when: ("consul_nodes" in group_names) and CONSUL_VM_ACL_ENABLED|bool
  ansible.builtin.shell:
    cmd: sed -i 's/^export CONSUL_HTTP_TOKEN=.*/export CONSUL_HTTP_TOKEN={{primary_bootstrap_token_fact}}/g' ~/.bashrc

- name: Create agent tokens for all nodes and save it to a local file.
  when: (CONSUL_VM_ACL_ENABLED|bool and "consul_nodes" in group_names)
  become: true
  ansible.builtin.shell:
    cmd: . ~/.bashrc 2>/dev/null && consul acl token create -node-identity=$(grep node_name /etc/consul.d/consul.hcl | cut -f 2 -d '=' | tr -d ' "'):$(grep '^datacenter' /etc/consul.d/consul-common.hcl | cut -f2 -d '"') | grep ^SecretID | tr -d ' ' | awk -F ':' '{print $2}' > /root/agent-token-after-federation.txt

- name: Set the newly created agent token read from /root/agent-token-after-federation.txt
  when: (CONSUL_VM_ACL_ENABLED|bool and "consul_nodes" in group_names)
  become: true
  ansible.builtin.shell:
    cmd: . ~/.bashrc 2>/dev/null && sleep 5 && consul acl set-agent-token agent $(cat /root/agent-token-after-federation.txt) && rm -f /root/agent-token-after-federation.txt

- debug: 
    msg: "Bootstrap token is: {{primary_bootstrap_token_fact}}"